---
extends:
  - eslint:recommended
  - react-app
  - react-app/jest
  - next
  - prettier
rules:
  react/prop-types: off
  '@typescript-eslint/explicit-module-boundary-types': off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
overrides:
  - files:
      - '**/*.stories.*'
    rules:
      import/no-anonymous-default-export: off
