service: serverless-bolt-js
frameworkVersion: 2
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:*'
          Resource:
            - "Fn::GetAtt": [ MessageDynamoDBTable, Arn ]
      tags:
        key: value
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-appsync-plugin
resources:
  Resources:
    ${file(./serverless.configs/dynamodb.table.message.yml)}
custom:
  appSync: ${file(./serverless.configs/appsync.yml)}